image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - "dotnet restore PaymentGateway.sln"

build:
    stage: build
    script:
        - "dotnet build PaymentGateway.sln"

test:
    stage: test
    script:
        - "dotnet test PaymentGateway.sln"
