// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PaymentGateway.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Payment
    {
        /// <summary>
        /// Initializes a new instance of the Payment class.
        /// </summary>
        public Payment()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Payment class.
        /// </summary>
        public Payment(System.Guid? id = default(System.Guid?), string cardNumber = default(string), string cardHolderName = default(string), int? expiryYear = default(int?), int? expiryMonth = default(int?), int? amount = default(int?), string currency = default(string), string cvv = default(string), bool? bankSuccess = default(bool?), string bankTransactionId = default(string))
        {
            Id = id;
            CardNumber = cardNumber;
            CardHolderName = cardHolderName;
            ExpiryYear = expiryYear;
            ExpiryMonth = expiryMonth;
            Amount = amount;
            Currency = currency;
            Cvv = cvv;
            BankSuccess = bankSuccess;
            BankTransactionId = bankTransactionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardNumber")]
        public string CardNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cardHolderName")]
        public string CardHolderName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expiryYear")]
        public int? ExpiryYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expiryMonth")]
        public int? ExpiryMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public int? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cvv")]
        public string Cvv { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bankSuccess")]
        public bool? BankSuccess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bankTransactionId")]
        public string BankTransactionId { get; set; }

    }
}
