// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PaymentGateway.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for PaymentGateway.
    /// </summary>
    public static partial class PaymentGatewayExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static Payment GetPayment(this IPaymentGateway operations, string id = default(string))
            {
                return operations.GetPaymentAsync(id).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Payment> GetPaymentAsync(this IPaymentGateway operations, string id = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetPaymentWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='payment'>
            /// </param>
            public static Payment ProcessPayment(this IPaymentGateway operations, ProcessPaymentRequest payment = default(ProcessPaymentRequest))
            {
                return operations.ProcessPaymentAsync(payment).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='payment'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Payment> ProcessPaymentAsync(this IPaymentGateway operations, ProcessPaymentRequest payment = default(ProcessPaymentRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ProcessPaymentWithHttpMessagesAsync(payment, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
